from exception import BaseException

class ArrayInitialisationException(BaseException):
    pass