from exception import Exception

class ArrayInitialisationException(BaseException):
    pass